#ifndef ATG_SIMPLE_2D_CONSTRAINT_SOLVER_SYSTEM_STATE_H
#define ATG_SIMPLE_2D_CONSTRAINT_SOLVER_SYSTEM_STATE_H

namespace atg_scs {
    class SystemState {
        public:
            SystemState();
            ~SystemState();

            //复制系统状态
            void copy(const SystemState *state);
            //扩大状态系统的规模至bodyCount或constraintCount，但是系统中的各项数据被清空。
            void resize(int bodyCount, int constraintCount);
            //将与刚体和约束相关的内存（即system_state中的所有指针）释放，释放后将n和n_c设置为0，dt不修改
            void destroy();

            void localToWorld(double x, double y, double *x_t, double *y_t, int body);
            void velocityAtPoint(double x, double y, double *v_x, double *v_y, int body);
            void applyForce(double x_l, double y_l, double f_x, double f_y, int body);

            //索引映射，用于将约束的索引映射到刚体的索引，n_c个约束，n_c个索引
            int *indexMap;

            //角加速度，用于计算角速度，n个刚体，n个角加速度
            double *a_theta;
            //角速度，用于计算角速度，n个刚体，n个角速度
            double *v_theta;
            //角度，用于计算角度，n个刚体，n个角度
            double *theta;

            //线加速度，用于计算线速度，n个刚体，n个线加速度
            double *a_x;
            double *a_y;
            //线速度，用于计算线速度，n个刚体，n个线速度
            double *v_x;
            double *v_y;
            //位置，用于计算位置，n个刚体，n个位置
            double *p_x;
            double *p_y;

            //力，用于计算力，n个刚体，n个力
            double *f_x;
            double *f_y;
            //力矩，用于计算力矩，n个刚体，n个力矩
            double *t;

            //Forces generated by Constraints to enforce rules.
            //Reaction forces，数量为约束两倍
            double *r_x;
            double *r_y;
            //Reaction torques.数量为约束两倍
            double *r_t;

            //质量，用于计算惯性力，n个刚体，n个质量
            double *m;
            //number of bodies，刚体的数量
            int n;
            //number of individual constraints，单独的约束的数量
            int n_c;
            //时间步长，用于模拟时间
            double dt;
    };
} /* namespace atg_scs */

#endif /* ATG_SIMPLE_2D_CONSTRAINT_SOLVER_SYSTEM_STATE_H */
