#ifndef ATG_SIMPLE_2D_CONSTRAINT_SOLVER_SYSTEM_STATE_H
#define ATG_SIMPLE_2D_CONSTRAINT_SOLVER_SYSTEM_STATE_H

namespace atg_scs {
    class SystemState {
        public:
            SystemState();
            ~SystemState();

            //复制系统状态
            void copy(const SystemState *state);
            //扩大状态系统的规模至bodyCount或constraintCount，但是系统中的各项数据被清空。
            void resize(int bodyCount, int constraintCount);
            //将与刚体和约束相关的内存（即system_state中的所有指针）释放，释放后将n和n_c设置为0，dt不修改
            void destroy();

            //将刚体body的局部坐标(x,y)转换为世界坐标(x_t,y_t)
            void localToWorld(double x, double y, double *x_t, double *y_t, int body);
            //计算body刚体上的点（x,y）在世界坐标系中的速度，保存在v_x和v_y中。注意（x,y）是刚体坐标系的本地坐标。
            void velocityAtPoint(double x, double y, double *v_x, double *v_y, int body);
            //对刚体body施加力（f_x,f_y），力作用在刚体坐标系的点（x_l,y_l）上
            //影响到this->f_x[body]和this->f_y[body]，以及this->t[body]，分别表示力在x方向和y方向的分量，以及力矩
            void applyForce(double x_l, double y_l, double f_x, double f_y, int body);

            //索引映射，用于将约束的索引映射到刚体的索引，n_c个约束，n_c个索引
            int *indexMap;

            //角加速度
            double *a_theta;
            //角速度
            double *v_theta;
            //角度
            double *theta;

            //刚体加速度
            double *a_x;
            double *a_y;
            //刚体线速度
            double *v_x;
            double *v_y;
            //n个刚体的世界坐标
            double *p_x;
            double *p_y;

            //n个刚体的受力
            double *f_x;
            double *f_y;
            //n个刚体的力矩，力矩=距离*力
            double *t;

            //Forces generated by Constraints to enforce rules.
            //Reaction forces，数量为约束两倍
            double *r_x;
            double *r_y;
            //Reaction torques.数量为约束两倍
            double *r_t;

            //n个刚体的质量
            double *m;
            //number of bodies，刚体的数量
            int n;
            //number of individual constraints，单独的约束的数量
            int n_c;
            //时间步长
            double dt;
    };
} /* namespace atg_scs */

#endif /* ATG_SIMPLE_2D_CONSTRAINT_SOLVER_SYSTEM_STATE_H */
